language: java
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8.2
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
# skip tests for now, fail because of non-headless JavaFX
script: mvn package -B -DskipTests=true -Dassembly.skipAssembly=true
