package miniceduapp.views

import javafx.scene.layout.Priority
import miniceduapp.viewmodels.BytecodeViewModel
import miniceduapp.views.editor.*
import miniceduapp.views.styles.Styles
import org.fxmisc.richtext.CodeArea
import tornadofx.*

class BytecodeView : View("Generated bytecode") {
    val viewModel: BytecodeViewModel by inject()

    var codeArea: CodeArea by singleAssign()

    override val root = hbox(10) {
        addClass(Styles.windowContent)
        codeArea = codeEditor(paneOp = {
            hgrow = Priority.ALWAYS
            vgrow = Priority.ALWAYS
        }) {
            addSyntaxHighlighting(MiniCSyntaxHighlighter())
            isEditable = false
            //showLineNumbers() // weird bug, onDock doesn't fire if called here
        }
        stackpane {
            hgrow = Priority.ALWAYS
            textarea(viewModel.bytecodeTextProperty) {
                hgrow = Priority.ALWAYS
            }

            imageview("loading.gif") {
                visibleWhen { viewModel.status.running }
            }
        }

    }

    init {
        viewModel.programCodeProperty.onChange {
            codeArea.replaceText(it)
        }

    }

    override fun onDock() {
        setWindowMinSize(800, 600)

        codeArea.showLineNumbers()

        viewModel.loadBytecode()
    }
}
